// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package infrastructure

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BoxType string

const (
	BoxTypeSAVING BoxType = "SAVING"
	BoxTypeWALLET BoxType = "WALLET"
)

func (e *BoxType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BoxType(s)
	case string:
		*e = BoxType(s)
	default:
		return fmt.Errorf("unsupported scan type for BoxType: %T", src)
	}
	return nil
}

type NullBoxType struct {
	BoxType BoxType
	Valid   bool // Valid is true if BoxType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBoxType) Scan(value interface{}) error {
	if value == nil {
		ns.BoxType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BoxType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBoxType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BoxType), nil
}

type DepositStatus string

const (
	DepositStatusACTIVE   DepositStatus = "ACTIVE"
	DepositStatusINACTIVE DepositStatus = "INACTIVE"
	DepositStatusCLOSED   DepositStatus = "CLOSED"
)

func (e *DepositStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DepositStatus(s)
	case string:
		*e = DepositStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DepositStatus: %T", src)
	}
	return nil
}

type NullDepositStatus struct {
	DepositStatus DepositStatus
	Valid         bool // Valid is true if DepositStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDepositStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DepositStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DepositStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDepositStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DepositStatus), nil
}

type FrequencyType string

const (
	FrequencyTypeINFINITY FrequencyType = "INFINITY"
	FrequencyTypeMONTHLY  FrequencyType = "MONTHLY"
	FrequencyTypeANNUAL   FrequencyType = "ANNUAL"
)

func (e *FrequencyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrequencyType(s)
	case string:
		*e = FrequencyType(s)
	default:
		return fmt.Errorf("unsupported scan type for FrequencyType: %T", src)
	}
	return nil
}

type NullFrequencyType struct {
	FrequencyType FrequencyType
	Valid         bool // Valid is true if FrequencyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrequencyType) Scan(value interface{}) error {
	if value == nil {
		ns.FrequencyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrequencyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrequencyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrequencyType), nil
}

type TransactionType string

const (
	TransactionTypeDEPOSIT  TransactionType = "DEPOSIT"
	TransactionTypeCREDIT   TransactionType = "CREDIT"
	TransactionTypeTRANSFER TransactionType = "TRANSFER"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType
	Valid           bool // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type Account struct {
	AccountID int32
	Name      string
}

// 実態のないボックスの入出金記録と、実際の口座からの入出金を紐づける。
type AccountBoxTransaction struct {
	BoxTransactionID     int32
	AccountTransactionID int32
}

type AccountTransaction struct {
	AccountTransactionID int32
	Description          string
	TransactionType      TransactionType
	Amount               int32
	AccountID            int32
	Timestamp            pgtype.Timestamp
}

type Box struct {
	BoxID              int32
	Type               BoxType
	Name               string
	DepositStatus      DepositStatus
	Frequency          FrequencyType
	AvailableDateStart interface{}
	AvailableDateEnd   interface{}
}

type BoxTransaction struct {
	BoxTransactionID int32
	ToBoxID          int32
	FromBoxID        pgtype.Int4
	Amount           int32
	Timestamp        pgtype.Timestamp
	TransactionType  TransactionType
}

type SavingBoxMetadatum struct {
	BoxID      pgtype.Int4
	GoalAmount int32
	GoalDate   interface{}
}
