// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package infrastructure

import (
	"context"
)

const getBox = `-- name: GetBox :one
SELECT box_id, type, name, deposit_status, frequency, available_date_start, available_date_end from box
WHERE box_id = $1
`

func (q *Queries) GetBox(ctx context.Context, boxID int32) (Box, error) {
	row := q.db.QueryRow(ctx, getBox, boxID)
	var i Box
	err := row.Scan(
		&i.BoxID,
		&i.Type,
		&i.Name,
		&i.DepositStatus,
		&i.Frequency,
		&i.AvailableDateStart,
		&i.AvailableDateEnd,
	)
	return i, err
}
