CREATE TYPE "box_type" AS ENUM (
  'SAVING',
  'WALLET'
);

CREATE TYPE "deposit_status" AS ENUM (
  'ACTIVE',
  'INACTIVE',
  'CLOSED'
);

CREATE TYPE "transaction_type" AS ENUM (
  'DEPOSIT',
  'CREDIT',
  'TRANSFER'
);

CREATE TYPE "frequency_type" AS ENUM (
  'INFINITY',
  'MONTHLY',
  'ANNUAL'
);

CREATE TABLE "account_transaction" (
  "account_transaction_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "description" varchar NOT NULL,
  "transaction_type" transaction_type NOT NULL,
  "amount" integer NOT NULL,
  "account_id" integer NOT NULL,
  "timestamp" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "account" (
  "account_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(2000) NOT NULL
);

CREATE TABLE "box" (
  "box_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "type" box_type NOT NULL,
  "name" varchar(2000) NOT NULL,
  "deposit_status" deposit_status NOT NULL,
  "frequency" frequency_type NOT NULL,
  "available_date_start" timestamp,
  "available_date_end" timestamp
);

CREATE TABLE "saving_box_metadata" (
  "box_id" integer,
  "goal_amount" integer NOT NULL,
  "goal_date" timestamp NOT NULL
);

CREATE TABLE "box_transaction" (
  "box_transaction_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "to_box_id" integer NOT NULL,
  "from_box_id" integer,
  "amount" integer NOT NULL,
  "timestamp" timestamp NOT NULL DEFAULT (now()),
  "transaction_type" transaction_type NOT NULL,
  CONSTRAINT "check_box_loop" CHECK (to_box_id != from_box_id)
);

CREATE TABLE "account_box_transaction" (
  "box_transaction_id" integer NOT NULL,
  "account_transaction_id" integer NOT NULL,
  PRIMARY KEY ("box_transaction_id", "account_transaction_id")
);

COMMENT ON TABLE "account_box_transaction" IS '実態のないボックスの入出金記録と、実際の口座からの入出金を紐づける。';

ALTER TABLE "saving_box_metadata" ADD FOREIGN KEY ("box_id") REFERENCES "box" ("box_id");

ALTER TABLE "box_transaction" ADD FOREIGN KEY ("to_box_id") REFERENCES "box" ("box_id");

ALTER TABLE "box_transaction" ADD FOREIGN KEY ("from_box_id") REFERENCES "box" ("box_id");

ALTER TABLE "account_transaction" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("account_id");

ALTER TABLE "account_box_transaction" ADD FOREIGN KEY ("account_transaction_id") REFERENCES "box_transaction" ("box_transaction_id");

ALTER TABLE "account_box_transaction" ADD FOREIGN KEY ("account_transaction_id") REFERENCES "account_transaction" ("account_transaction_id");
